// Integrate workflow-generated content + art into the project.
// Usage: node tools/integrate.mjs <workflow-output-file>
// Supports two pack formats:
//   - { artCode, contentCode }  -> writes art/gen + content/gen files
//   - { code }                  -> writes a single content/gen file (mega header)
// Indexes are rebuilt by SCANNING the gen dirs, so prior packs are preserved.
import fs from 'fs';
import path from 'path';

const outFile = process.argv[2];
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const ART_DIR = path.join(ROOT, 'src', 'art', 'gen');
const CONTENT_DIR = path.join(ROOT, 'src', 'game', 'content', 'gen');
fs.mkdirSync(ART_DIR, { recursive: true });
fs.mkdirSync(CONTENT_DIR, { recursive: true });

const decode = (s) => (s || '')
  .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&#x27;/g, "'")
  .replace(/&amp;/g, '&');
const sanitize = (s) => decode(s)
  .split('\n')
  .filter((l) => !/^\s*import\s.+from\s.+;?\s*$/.test(l))
  .map((l) => l.replace(/^\s*export\s+(const|function|let|class)\b/, '$1'))
  .join('\n');

const ART_HEADER = `// AUTO-GENERATED by workflow — art.
import { defineSprite, defineAnim, Painter } from '../../engine/sprites.js';
import { P, lighten, darken, mix, withAlpha } from '../../engine/palette.js';
import { defineIcon, panel, sym } from '../icons.js';
import { drawSlime, drawBat, drawWisp, drawBrute, drawHunter } from '../core.js';

`;
const CONTENT_HEADER = `// AUTO-GENERATED by workflow — content.
import { Enemies, Items, Equipment, Abilities, Talents, Facilities, Weapons, Characters } from '../registry.js';
import { P, lighten, darken, mix, withAlpha } from '../../../engine/palette.js';
import { dist, dist2, rng, clamp, TAU } from '../../../engine/math.js';
import { Projectile } from '../../projectile.js';

`;
// mega header for single-blob packs that mix art + logic (weapons/characters)
const MEGA_HEADER = `// AUTO-GENERATED by workflow — content + art.
import { Enemies, Items, Equipment, Abilities, Talents, Facilities, Weapons, Characters } from '../registry.js';
import { P, lighten, darken, mix, withAlpha } from '../../../engine/palette.js';
import { dist, dist2, rng, clamp, TAU } from '../../../engine/math.js';
import { Projectile } from '../../projectile.js';
import { glowWorld, fillCircleWorld, drawSprite, lineWorld } from '../../../engine/renderer.js';
import { getSprite, defineSprite, defineAnim, Painter } from '../../../engine/sprites.js';
import { defineIcon, panel, sym } from '../../../art/icons.js';
import { drawSlime, drawBat, drawWisp, drawBrute, drawHunter } from '../../../art/core.js';
import { Sfx } from '../../../engine/audio.js';

`;

const raw = fs.readFileSync(outFile, 'utf8');
const data = JSON.parse(raw);
const packs = Array.isArray(data) ? data : data.result;
if (!Array.isArray(packs)) { console.error('no result array'); process.exit(1); }

let totalIds = 0, totalSprites = 0;
const report = [];
for (const pack of packs) {
  if (!pack || !pack.key) continue;
  const key = pack.key.replace(/[^a-z0-9_]/gi, '_');
  if (pack.code && pack.code.trim()) {
    fs.writeFileSync(path.join(CONTENT_DIR, key + '.js'), MEGA_HEADER + sanitize(pack.code) + '\n');
  } else {
    if (pack.artCode && pack.artCode.trim()) fs.writeFileSync(path.join(ART_DIR, key + '.js'), ART_HEADER + sanitize(pack.artCode) + '\n');
    if (pack.contentCode && pack.contentCode.trim()) fs.writeFileSync(path.join(CONTENT_DIR, key + '.js'), CONTENT_HEADER + sanitize(pack.contentCode) + '\n');
  }
  totalIds += (pack.ids || []).length;
  totalSprites += (pack.spriteNames || []).length;
  report.push(`  ${pack.key}: ${(pack.ids || []).length} ids, ${(pack.spriteNames || []).length} sprites, ok=${pack.ok}${pack.issues ? ' | ' + String(pack.issues).slice(0, 70) : ''}`);
}

// rebuild indexes by scanning the dirs (keeps every pack ever written)
function buildIndex(dir, tag) {
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.js') && f !== 'index.js').map((f) => f.replace(/\.js$/, ''));
  const idx = `// AUTO-GENERATED index (dynamic import = fault isolation).
const PACKS = ${JSON.stringify(files)};
for (const m of PACKS) {
  try { await import('./' + m + '.js'); }
  catch (e) { console.warn('[${tag}] pack failed to load:', m, e && e.message); }
}
export const ${tag.toUpperCase().replace(/-/g, '_')}_PACKS = PACKS;
`;
  fs.writeFileSync(path.join(dir, 'index.js'), idx);
  return files;
}
const artFiles = buildIndex(ART_DIR, 'gen-art');
const contentFiles = buildIndex(CONTENT_DIR, 'gen-content');

console.log('=== integration report ===');
console.log(report.join('\n'));
console.log(`art gen files: ${artFiles.length}, content gen files: ${contentFiles.length}`);
console.log(`this run: ${totalIds} ids, ${totalSprites} sprites`);
